// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnplWAx0sGF1HfY5qPSeVOJQKrkozEs0o',
    appId: '1:805126511699:web:a73ff9c9f84ed762fefaa6',
    messagingSenderId: '805126511699',
    projectId: 'fir-flutter-codelab-3abac',
    authDomain: 'fir-flutter-codelab-3abac.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-3abac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA97iqWihui0B9fzG9KJrqxUxzp89gsC-E',
    appId: '1:805126511699:android:aee053e059093a5bfefaa6',
    messagingSenderId: '805126511699',
    projectId: 'fir-flutter-codelab-3abac',
    storageBucket: 'fir-flutter-codelab-3abac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUkwuliMsOlt-16-M8gEEqGZ9szHkKqRw',
    appId: '1:805126511699:ios:a52bec3fab39a2d4fefaa6',
    messagingSenderId: '805126511699',
    projectId: 'fir-flutter-codelab-3abac',
    storageBucket: 'fir-flutter-codelab-3abac.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUkwuliMsOlt-16-M8gEEqGZ9szHkKqRw',
    appId: '1:805126511699:ios:a52bec3fab39a2d4fefaa6',
    messagingSenderId: '805126511699',
    projectId: 'fir-flutter-codelab-3abac',
    storageBucket: 'fir-flutter-codelab-3abac.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
